# Generated by Django 4.1 on 2023-06-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zookeeper",
            name="zkp_cpw",
            field=models.CharField(
                default=models.CharField(default="0602", max_length=50), max_length=50
            ),
        ),
        migrations.AddField(
            model_name="zookeeper",
            name="zkp_join",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 15, 18, 36, 1599)
            ),
        ),
        migrations.AddField(
            model_name="zookeeper",
            name="zkp_pw",
            field=models.CharField(default="0602", max_length=50),
        ),
    ]
