# Generated by Django 4.1 on 2023-06-10 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0002_zookeeper_zkp_cpw_zookeeper_zkp_join_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zookeeper",
            name="zkp_join",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 15, 29, 16, 311446)
            ),
        ),
    ]
