# Generated by Django 4.1 on 2023-06-10 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0003_alter_zookeeper_zkp_join"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zookeeper",
            name="zkp_cpw",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="zookeeper",
            name="zkp_join",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 10, 15, 35, 35, 992624)
            ),
        ),
        migrations.AlterField(
            model_name="zookeeper",
            name="zkp_pw",
            field=models.CharField(max_length=50),
        ),
    ]
