# Generated by Django 4.1 on 2023-06-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0004_alter_zookeeper_zkp_cpw_alter_zookeeper_zkp_join_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zookeeper",
            name="zkp_join",
            field=models.DateTimeField(),
        ),
    ]
