# Generated by Django 4.1 on 2023-06-12 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0005_alter_zookeeper_zkp_join"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detaillog",
            name="anm",
        ),
    ]
