# Generated by Django 4.1 on 2023-06-12 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0006_remove_detaillog_anm"),
    ]

    operations = [
        migrations.AddField(
            model_name="detaillog",
            name="anm",
            field=models.ForeignKey(
                default=111,
                on_delete=django.db.models.deletion.CASCADE,
                to="Zoo.animal",
            ),
        ),
    ]
