# Generated by Django 4.1 on 2023-06-13 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0007_detaillog_anm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="anm_birth",
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_old",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
