# Generated by Django 4.1 on 2023-06-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0008_remove_animal_anm_birth_animal_anm_old"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklog",
            name="clog_bf",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checklog",
            name="clog_dn",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checklog",
            name="clog_em",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checklog",
            name="clog_lch",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checklog",
            name="clog_lm",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="checklog",
            name="clog_mm",
            field=models.BooleanField(default=False),
        ),
    ]
