# Generated by Django 4.1 on 2023-06-14 05:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0009_alter_checklog_clog_bf_alter_checklog_clog_dn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="anm_img",
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_bf",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_dn",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_em",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_food",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_lch",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_lm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_mc",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_mm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_tm",
            field=models.TimeField(
                default=datetime.datetime(2023, 6, 14, 14, 3, 13, 637199)
            ),
        ),
    ]
