# Generated by Django 4.1 on 2023-06-14 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0010_remove_animal_anm_img_animal_anm_bf_animal_anm_dn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="anm_bf",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_dn",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_em",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_food",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_lch",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_lm",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_mc",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_mm",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="anm_tm",
        ),
    ]
