# Generated by Django 4.1 on 2023-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0011_remove_animal_anm_bf_remove_animal_anm_dn_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="checklog",
            name="clog_food",
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
