# Generated by Django 4.1 on 2023-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0012_alter_checklog_clog_food"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="checklog",
            name="anm_id",
        ),
        migrations.AddField(
            model_name="checklog",
            name="clog_id",
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
