# Generated by Django 4.1 on 2023-06-14 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0013_remove_checklog_anm_id_checklog_clog_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="anm_check",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_food",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_mc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_tm",
            field=models.TimeField(default=datetime.time(23, 44, 40, 34550)),
        ),
    ]
