# Generated by Django 4.1 on 2023-06-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0014_animal_anm_check_animal_anm_food_animal_anm_mc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="anm_tm",
            field=models.TimeField(null=True),
        ),
    ]
