# Generated by Django 4.1 on 2023-06-14 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0015_alter_animal_anm_tm"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="anm_tm",
        ),
    ]
