# Generated by Django 4.1 on 2023-06-19 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0016_remove_animal_anm_tm"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="anm_join",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 19, 14, 17, 34, 492072)
            ),
        ),
        migrations.AddField(
            model_name="animal",
            name="anm_last",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 6, 19, 14, 17, 34, 492072)
            ),
        ),
    ]
