# Generated by Django 4.1 on 2023-06-19 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Zoo", "0017_animal_anm_join_animal_anm_last"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="anm_join",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 6, 19, 14, 21, 38, 730591),
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="anm_last",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(2023, 6, 19, 14, 21, 38, 730591),
                null=True,
            ),
        ),
    ]
